#!/usr/bin/env php
<?php

declare(strict_types=1);

use Laminas\Internal\Migrations\GitAttributes;
use Laminas\Internal\Migrations\ProjectInformation;

require __DIR__ . '/../autoloader.php';

/** @var mixed $rootDirectory */
$rootDirectory = $argv[1] ?? null;
if (
    ! is_string($rootDirectory)
    || $rootDirectory === ''
    || ! is_dir($rootDirectory)
) {
    throw new RuntimeException('Pass a single argument representing the root directory of the target library');
}

$project = ProjectInformation::fromDirectory($rootDirectory);
$attributes = new GitAttributes($project->gitAttributes);
$attributes->unignore('psalm.xml');
$attributes->unignore('psalm.xml.dist');
$attributes->unignore('psalm-baseline.xml');
