#!/usr/bin/env php
<?php

declare(strict_types=1);

use Laminas\Internal\Migrations\ComposerFile;
use Laminas\Internal\Migrations\LaminasCI;
use Laminas\Internal\Migrations\LaminasCIWorkflow;
use Laminas\Internal\Migrations\MagoConfig;
use Laminas\Internal\Migrations\Makefile;
use Laminas\Internal\Migrations\ProjectInformation;

require __DIR__ . '/../autoloader.php';

/** @var mixed $rootDirectory */
$rootDirectory = $argv[1] ?? null;
if (
    ! is_string($rootDirectory)
    || $rootDirectory === ''
    || ! is_dir($rootDirectory)
) {
    throw new RuntimeException('Pass a single argument representing the root directory of the target library');
}

$project = ProjectInformation::fromDirectory($rootDirectory);

// Patch Composer
$composer = new ComposerFile($project->composerFile);
$composer->setPlatform('8.3.99');
$composer->setPhpVersionConstraint('~8.3 || ~8.4 || ~8.5 || ~8.6');
$composer->write();

// Enable BC Checker and Ignore Platform Reqs on 8.6
if ($project->laminasCiConfig !== null) {
    $laminasCi = new LaminasCI($project->laminasCiConfig);
    $laminasCi->enableBcChecker();
    $laminasCi->ignorePlatformReqsOnlyOn('8.6');
    $laminasCi->write();
}

// Check for a `default_php` environment variable used in custom jobs
$workflowDirectory = sprintf(
    '%s/%s',
    $project->projectDirectory,
    '.github/workflows',
);

if (is_dir($workflowDirectory)) {
    $iterator = new DirectoryIterator($workflowDirectory);
    foreach ($iterator as $item) {
        if (! $item->isFile() || $item->isDot()) {
            continue;
        }

        if (! preg_match('/(.yml|.yaml)$/', $item->getBasename())) {
            continue;
        }

        $workflow = new LaminasCIWorkflow($item->getRealPath());
        $workflow->setDefaultPHPEnvironmentVariableIfPresent('8.3');
        $workflow->write();
    }
}

// Update Mago Configuration if necessary
if ($project->magoConfiguration !== null) {
    $mago = new MagoConfig($project->magoConfiguration);
    $mago->setPhpVersionWhenPresentTo('8.3.0');
    $mago->write();
}

// Update the PHP_VERSION env var in the Project Makefile if it can be found
if ($project->makefile !== null) {
    $makefile = new Makefile($project->makefile);
    $makefile->updatePHPVersionTo('8.3');
}

// Update the composer files for anything in the tools directory
$toolsDirectory = $project->projectDirectory . '/tools';
if (is_dir($toolsDirectory) && file_exists($toolsDirectory)) {
    $iterator = new DirectoryIterator($toolsDirectory);
    /** @var SplFileInfo&DirectoryIterator $item */
    foreach ($iterator as $item) {
        if ($item->isDot() || ! $item->isDir()) {
            continue;
        }

        $file = $item->getRealPath() . '/composer.json';
        if (! file_exists($file)) {
            continue;
        }

        $composer = new ComposerFile($file);
        $composer->setPlatform('8.3.99');
        $composer->setPhpVersionConstraint('~8.3 || ~8.4 || ~8.5 || ~8.6');
        $composer->write();
    }
}
